export const CHAT_LINE_MESSAGE = 'chat-line__message'
export const CHAT_NOTICE_MESSAGE = 'user-notice-line'
export const CHAT_DISPLAY_NAME = 'chat-author__display-name'
export const DATA_USER_ID = 'data-user-id'
export const STORAGE_KEY = 'customNames'
